INSERT INTO PERSON (name) VALUES('Rafał');
INSERT INTO PERSON (name) VALUES('Adam');
INSERT INTO PERSON (name) VALUES('Tomasz');
INSERT INTO PERSON (name) VALUES('Jan');

INSERT INTO RENT_OBJECT ( AREA , DESCRIPTION , NAME , PRICE ) VALUES (10, 'Test1', 'Name1', 100);
INSERT INTO RENT_OBJECT ( AREA , DESCRIPTION , NAME , PRICE ) VALUES (12, 'Test2', 'Name2', 200);
INSERT INTO RENT_OBJECT ( AREA , DESCRIPTION , NAME , PRICE ) VALUES (14, 'Test3', 'Name3', 400);
INSERT INTO RENT_OBJECT ( AREA , DESCRIPTION , NAME , PRICE ) VALUES (16, 'Test4', 'Name4', 80);

INSERT INTO RESERVATION ( DATE_FROM , DATE_TO , DESCRIPTION , PERSON_ID , PRICE , RENT_OBJECT_ID ) VALUES  ('2022-08-20', '2022-08-29', 'reservation', 1, 200, 1);
INSERT INTO RESERVATION ( DATE_FROM , DATE_TO , DESCRIPTION , PERSON_ID , PRICE , RENT_OBJECT_ID ) VALUES  ('2022-09-10', '2022-09-12', 'reservation', 1, 200, 1);
INSERT INTO RESERVATION ( DATE_FROM , DATE_TO , DESCRIPTION , PERSON_ID , PRICE , RENT_OBJECT_ID ) VALUES  ('2022-08-29', '2022-09-29', 'reservation2', 2, 300, 2);
INSERT INTO RESERVATION ( DATE_FROM , DATE_TO , DESCRIPTION , PERSON_ID , PRICE , RENT_OBJECT_ID ) VALUES  ('2022-08-29', '2022-09-29', 'reservation3', 1, 400, 1);
INSERT INTO RESERVATION ( DATE_FROM , DATE_TO , DESCRIPTION , PERSON_ID , PRICE , RENT_OBJECT_ID ) VALUES  ('2022-08-29', '2022-09-29', 'reservation4', 3, 500, 3);